collections:

  grammar:
    output: true
    permalink: /:collection/:name

  idiom:
    output: true
    permalink: /:collection/:name

  slang:
    output: true
    permalink: /:collection/:name
  
  vocabulary:
    output: true
    permalink: /:collection/:name